version: "3.9"
services:
    database:
        image: postgres:alpine
        restart: unless-stopped
        container_name: moldagroteh-database
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${DB_DATABASE}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - ./storage/docker/_db:/var/lib/postgresql/data
        networks:
            - moldagroteh-database-network

    moldagroteh-app:
        build:
            context: ./
            dockerfile: ./docker/php/Dockerfile
        container_name: moldagroteh-app
        user: ${UID}:${GID}
        restart: unless-stopped
        volumes:
            - ./:/var/www/html
            - ./docker/php/extend-php.ini:/usr/local/etc/php/conf.d/extend-php.ini
        depends_on:
            - database
        networks:
            - moldagroteh-database-network
            - moldagroteh-app-network

    webserver:
        image: nginx:alpine
        restart: unless-stopped
        container_name: webserver
        volumes:
            - ./:/var/www/html
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
            - ./storage/docker/logs/nginx/:/var/log/nginx/
        ports:
            - "8080:80"
        networks:
            - moldagroteh-app-network
networks:
    moldagroteh-database-network:
    moldagroteh-app-network:
